privateKey:
  algorithm: RSA
  size: 2048

usages:
  - digital signature
  - key encipherment
  - server auth

certificates:
  - name: api-gateway-tls
    secretName: api-gateway-tls
    issuer: letsencrypt-staging
    commonName: api.stage.microbankapp.com
    dnsNames:
      - api.stage.microbankapp.com

  - name: keycloak-tls
    secretName: keycloak-tls
    issuer: letsencrypt-staging
    commonName: auth.stage.microbankapp.com
    dnsNames:
      - auth.stage.microbankapp.com