apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: transaction-service
  namespace: transaction-service
spec:
  host: transaction-service.transaction-service.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 20
        idleTimeout: 30s
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 60s
      maxEjectionPercent: 50