apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limit-range
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 500m
        memory: 1Gi
      default:
        cpu: "2"
        memory: 4Gi
      min:
        cpu: 250m
        memory: 512Mi
      max:
        cpu: "8"
        memory: 16Gi