apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-resource-quota
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "100"
    services: "20"
    configmaps: "100"
    secrets: "100"
    persistentvolumeclaims: "30"
    requests.storage: 1Ti