apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-load-balancer-controller
  - external-dns
  - external-secrets
  - ebs-csi-driver
  - monitoring
  - cert-manager
  - kyverno
  - falco
  - istio-system
  - microbank-account
  - microbank-apigateway
  - microbank-auth
  - microbank-document
  - microbank-notification
  - microbank-transaction