apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microbank-document

resources:
  - allow-dns.yaml
  - allow-amazonmq.yaml
  - allow-rds-postgres.yaml
  - allow-keycloak.yaml
  - allow-document-service.yaml
  - allow-auth-service.yaml
  - allow-account-service.yaml