apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: s3
  namespace: istio-system
spec:
  host: s3.ap-south-1.amazonaws.com
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        maxRequestsPerConnection: 20
        idleTimeout: 30s
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50