apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-s3
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: document-service
  policyTypes:
    - Egress
  egress: []