clusterIssuers:

  - name: selfsigned-cluster-issuer
    type: selfSigned

  - name: letsencrypt
    type: acme

    email: rajaramandps@gmail.com

    server: https://acme-staging-v02.api.letsencrypt.org/directory

    privateKeySecret: letsencrypt-account-key

    ingressClass: nginx