apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: s3
  namespace: istio-system
spec:
  hosts:
   - s3.ap-south-1.amazonaws.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL