{{- if .Values.secrets.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ include "kyverno.secrets.policyName" . }}
  annotations:
    policies.kyverno.io/title: Secret Governance
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod,Secret
    policies.kyverno.io/description: |
      Enforces enterprise secret management standards.
spec:
  validationFailureAction: {{ .Values.global.validationFailureAction }}
  background: {{ .Values.global.background }}
  failurePolicy: {{ .Values.global.failurePolicy }}
  emitWarning: {{ .Values.global.emitWarning }}
  rules:
{{ include "kyverno.secrets.rule.disallowInlineSecrets" . | nindent 4 }}

{{ include "kyverno.secrets.rule.restrictSecretTypes" . | nindent 4 }}

{{/*
{{ include "kyverno.secrets.rule.requireSecretReferences" . | nindent 4 }}

{{ include "kyverno.secrets.rule.requireReadOnlySecretMounts" . | nindent 4 }}
*/}}

{{- end }}