apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
  {{- include "microservice.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "microservice.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.configMap.enabled }}
          checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.secret.enabled }}
          checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "microservice.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.initContainers }}
      initContainers:
      {{ toYaml .Values.initContainers | nindent 8 }}
      {{ end }}
      containers:
      - name: {{ include "microservice.name" . }}
##      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        image: "{{ .Values.image.repository }}@{{ required "image.digest is required" .Values.image.digest }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - name: http
          containerPort: {{ .Values.containerPorts.http }}
          protocol: TCP
        - name: management
          containerPort: {{ .Values.containerPorts.management }}
          protocol: TCP
        {{- if or .Values.configMap.enabled .Values.secret.enabled }}
        envFrom:
        {{ if .Values.configMap.enabled }}
        - configMapRef:
            name: {{ include "microservice.fullname" . }}
        {{- end }}
        {{ if .Values.secret.enabled }}
        - secretRef:
            name: {{ include "microservice.fullname" . }}
        {{- end }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          {{ toYaml .Values.readinessProbe.config | nindent 10 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          {{ toYaml .Values.livenessProbe.config | nindent 10 }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe:
          {{ toYaml .Values.startupProbe.config | nindent 10 }}
        {{- end }}
        {{- if .Values.resources.enabled }}
        resources:
          requests:
            {{- toYaml .Values.resources.requests | nindent 12 }}
          limits:
            {{- toYaml .Values.resources.limits | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      {{- if .Values.affinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "microservice.selectorLabels" . | nindent 14 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "microservice.selectorLabels" . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}