{{- if and .Values.secret.enabled (not .Values.externalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type | default "Opaque" }}
stringData:
{{- with .Values.secret.data }}
  {{ toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.secret.files }}
  {{- range $key,$value := . }}
    {{ $key }}: |
{{ $value | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}