apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-keycloak-from-ingress
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  podSelector:
    matchLabels:
      network-role: identity

  policyTypes:
    - Ingress

  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          tier: ingress
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080