apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rabbitmq-from-workloads
  namespace: rabbitmq
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  
  policyTypes:
  - Ingress

  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          tier: workloads
      podSelector:
        matchLabels:
          access.rabbitmq: "true"
    ports:
    - protocol: TCP
      port: 5672
  - from:
    - namespaceSelector:
        matchLabels:
          tier: ingress
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 15672

  