{{- if .Values.metadata.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ include "kyverno.metadata.policyName" . }}
  annotations:
    policies.kyverno.io/title: Metadata Governance
    policies.kyverno.io/category: Governance
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: |
      Enforces enterprise metadata standards for workloads.
spec:
  validationFailureAction: {{ .Values.global.validationFailureAction }}
  background: {{ .Values.global.background }}
  failurePolicy: {{ .Values.global.failurePolicy }}
  emitWarning: {{ .Values.global.emitWarning }}
  rules:
{{ include "kyverno.metadata.rule.requiredLabels" . | nindent 4 }}

{{ include "kyverno.metadata.rule.requiredAnnotations" . | nindent 4 }}

{{/*
Future Rules

{{ include "kyverno.metadata.rule.recommendedLabels" . | nindent 4 }}

{{ include "kyverno.metadata.rule.immutableLabels" . | nindent 4 }}

{{ include "kyverno.metadata.rule.immutableAnnotations" . | nindent 4 }}

*/}}

{{- end }}