apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mq-
  namespace: istio-system
spec:
  hosts:
  - vpce-xyz.mq.ap-south-1.vpce.amazonaws.com
  gateways:
  - mesh
  - egress-gateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 5671
      sniHosts:
      - vpce-xyz.mq.ap-south-1.vpce.amazonaws.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 5671
  - match:
    - gateways:
      - egress-gateway
      port: 5671
      sniHosts:
      - vpce-xyz.mq.ap-south-1.vpce.amazonaws.com
    route:
    - destination:
        host: vpce-xyz.mq.ap-south-1.vpce.amazonaws.com
        port:
          number: 5671