apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/Rajaraman-Ramanathan/microbank-platform-gitops.git
      targetRevision: stage
      path: platform/security/cert-manager/helm
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/environments/stage/cert-manager/values.yaml
    - repoURL: https://github.com/Rajaraman-Ramanathan/microbank-platform-gitops.git
      targetRevision: stage
      ref: values
  destination:
    name: microbank-stage-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true