apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/Rajaraman-Ramanathan/microbank-platform-gitops.git
      targetRevision: stage
      path: platform/aws/external-secrets/helm
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/environments/stage/external-secrets/values.yaml
    - repoURL: https://github.com/Rajaraman-Ramanathan/microbank-platform-gitops.git
      targetRevision: stage
      ref: values
  destination:
    name: microbank-stage-cluster
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true