apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resource-quotas
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: platform
  source:
    repoURL: https://github.com/Rajaraman-Ramanathan/microbank-platform-gitops.git
    targetRevision: stage
    path: platform/governance/resource-quotas
  destination:
    name: microbank-stage-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true