apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microbank-account

resources:
  - allow-auth-service.yaml
  - allow-dns.yaml
  - allow-keycloak.yaml
  - allow-rds-postgres.yaml