apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: keycloak
  namespace: istio-system
spec:
  host: auth.microbank.internal
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        maxRequestsPerConnection: 20
        idleTimeout: 30s
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 60s
      maxEjectionPercent: 50