apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-workloads-to-minio
  namespace: microbank-dev
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  podSelector:
    matchLabels:
      network-role: backend

  policyTypes:
  - Egress

  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          tier: platform
      podSelector:
        matchLabels:
          network-role: platform
          app.kubernetes.io/name: minio
    ports:
    - protocol: TCP
      port: 9000