apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microbank-account

resources:
  - allow-from-gateway.yaml
  - allow-from-prometheus.yaml
  - allow-from-transaction-service.yaml