apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-amazonmq
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  policyTypes:
    - Egress
  egress: []