apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- account-service-strict.yaml
- auth-service-strict.yaml
- document-service-strict.yaml
- notification-service-strict.yaml
- transaction-service-strict.yaml