apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: amazonmq
  namespace: istio-system
spec:
  host: vpce-xyz.mq.ap-south-1.vpce.amazonaws.com
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 60s
      maxEjectionPercent: 50