{{- if .Values.storage.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ include "kyverno.storage.policyName" . }}
  annotations:
    policies.kyverno.io/title: Storage Security
    policies.kyverno.io/category: Runtime Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod,PersistentVolumeClaim
    policies.kyverno.io/description: |
      Enforces enterprise storage governance for
      application workloads.
spec:
  validationFailureAction: {{ .Values.global.validationFailureAction }}
  background: {{ .Values.global.background }}
  failurePolicy: {{ .Values.global.failurePolicy }}
  emitWarning: {{ .Values.global.emitWarning }}
  rules:
{{ include "kyverno.storage.rule.disallowHostPath" . | nindent 4 }}

{{ include "kyverno.storage.rule.requireStorageClass" . | nindent 4 }}

{{ include "kyverno.storage.rule.allowedAccessModes" . | nindent 4 }}

{{ include "kyverno.storage.rule.volumeMode" . | nindent 4 }}

{{/*
{{ include "kyverno.storage.rule.pvcSizeLimit" . | nindent 4 }}

{{ include "kyverno.storage.rule.readOnlyVolumes" . | nindent 4 }}
*/}}

{{- end }}