# -----------------------------------------------------------------------------
# Java Application Accessing Sensitive File
# -----------------------------------------------------------------------------

- rule: Java Application Accessing Sensitive File

  desc: >
    Detect Java application processes accessing
    sensitive operating system files.

  condition: >
    open_read
    and java_process
    and sensitive_file_access
    and not trusted_platform_component

  output: >
    Java application accessed sensitive file
    (user=%user.name
    command=%proc.cmdline
    file=%fd.name
    container=%container.name
    image=%container.image.repository
    namespace=%k8s.ns.name
    pod=%k8s.pod.name)

  priority: ERROR

  tags:
    - filesystem
    - application
    - sensitive-file

#
# -----------------------------------------------------------------------------
# Shell Accessing Sensitive File
# -----------------------------------------------------------------------------

- rule: Shell Accessing Sensitive File

  desc: >
    Detect shell processes reading sensitive files
    inside application containers.

  condition: >
    open_read
    and shell_process
    and sensitive_file_access
    and not trusted_platform_component

  output: >
    Shell accessed sensitive file
    (user=%user.name
    command=%proc.cmdline
    file=%fd.name
    container=%container.name
    namespace=%k8s.ns.name
    pod=%k8s.pod.name)

  priority: WARNING

  tags:
    - filesystem
    - shell
    - sensitive-file

# -----------------------------------------------------------------------------
# Interpreter Accessing Sensitive File
# -----------------------------------------------------------------------------

- rule: Interpreter Accessing Sensitive File

  desc: >
    Detect scripting language interpreters accessing
    sensitive files inside application containers.

  condition: >
    open_read
    and interpreter_process
    and sensitive_file_access
    and not trusted_platform_component

  output: >
    Interpreter accessed sensitive file
    (user=%user.name
    command=%proc.cmdline
    file=%fd.name
    container=%container.name
    namespace=%k8s.ns.name
    pod=%k8s.pod.name)

  priority: WARNING

  tags:
    - filesystem
    - interpreter
    - sensitive-file