apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: ses
  namespace: istio-system
spec:
  hosts:
    - vpce-abc123.email.ap-south-1.vpce.amazonaws.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL