apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
  namespace: ${ARGOCD_NAMESPACE}
  labels:
    argocd.argoproj.io/secret-type: cluster
    microbank.io/environment: ${ENVIRONMENT}
    microbank.io/managed-by: github-actions
type: Opaque
stringData:
  name: ${CLUSTER_NAME}
  server: ${SERVER}
  config: |
    {
      "bearerToken": "${BEARER_TOKEN}",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "${CA_DATA}"
      }
    }